remote_theme: mmistakes/minimal-mistakes

plugins:
  # - jekyll-paginate
  # - jekyll-sitemap
  # - jekyll-gist
  # - jekyll-feed
  # - jemoji
  - jekyll-include-cache
  - jekyll-titles-from-headings

# https://talk.jekyllrb.com/t/title-derived-from-heading-appears-twice-on-top-of-page/1686/4?u=mmistakes
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

# search: true
author: "Jim Kring"
title: "GitHub Actions in 7 Minutes"
subtitle: "Automating Development Tasks in the Cloud"
description: "A short presentation by Jim Kring on July 20, 2022 at GDevCon NA in Golden Colorado, USA."

masthead_title: "GitHub Actions in 7 Minutes (Automating Development Tasks in the Cloud)"
masthead_subtitle: "Presented by Jim Kring on July 20, 2022 at GDevCon NA in Golden Colorado, USA"

atom_feed:
  hide: true

defaults:
  # _posts
  - scope:
      path: ""
      type: slides
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
      
      
