remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# search: true

title: "GitHub Actions in 7 Minutes"
subtitle: "Automating Development Tasks in the Cloud"
description: "A short presentation by Jim Kring on July 20, 2022 at GDevCon NA in Golden Colorado, USA."

atom_feed:
  hide: true

defaults:
  # _posts
  - scope:
      path: ""
      type: slides
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: false
